### ISSUE TITLE
One more CSLinearLayout on screen

### ISSUE THREAD

**Issue by mecid** [scalessec/CSLinearLayoutView#1]

**Comment by scalessec** [comment]
I'm not entirely sure what you're asking. All sizeToFit does on a UIView is call sizeThatFits: ... And that, by default, doesn't really do anything. It's your job to override sizeThatFits: in your UIView subclass to provide the intended behavior (this is what UILabel does). http://developer.apple.com/library/ios/#documentation/uikit/reference/uiview_class/UIView/UIView.html 

Although, like I said, I'm not entirely clear what you're trying to do.
